# -*- coding: utf-8 -*-
"""Progress TTU 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EmAhqsHMfaxwxpDqs2Rqduxnj9WbD5OP
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Preparing Data"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/TTU 2/Merged Dataset Final.csv")
df

df = df.rename(columns={'full_text': 'Text'})

"""# Data Cleaning"""

df.drop(columns = ["image_url", "in_reply_to_screen_name", "location", "conversation_id_str", "created_at", "favorite_count", "id_str", "lang", "quote_count", "reply_count", "retweet_count", "tweet_url", "user_id_str", "username"], axis = 1, inplace = True)

df

# Menghitung duplikasi pada kolom 'full_text'
duplicate_count_tweet = df.duplicated(subset=['Text']).sum()
print(f"Jumlah data duplikat pada kolom Text : {duplicate_count_tweet}")

# Menampilkan duplikasi dalam data
duplicate_rows = df[df.duplicated(subset=['Text'], keep=False)]
duplicate_rows

# Menghapus duplikat pada kolom 'Text' dan menyimpannya pada variabel tweet_cleaned
tweet = df.drop_duplicates(subset=['Text'], keep='first')

# Menampilkan jumlah data setelah duplikat dihapus
print(f"Jumlah data setelah eliminasi duplikat : {tweet.shape[0]}")

import re

def remove (text):
  # Mendefinisikan kata kunci
  keywords = ["toktokers", "geoya", "hide", "vcs", "g0als"]

  # Menggunakan ekspresi reguler untuk menemukan kata kunci, bahkan jika berada di dalam kata lain
  for keyword in keywords:
    if re.search(r'\b' + re.escape(keyword) + r'\b', text): # \b memastikan pencocokan kata utuh
      return "" # Atau kembalikan np.nan, tergantung pada apa yang ingin Anda lakukan dengan baris yang dihapus

  return text

# Menerapkan fungsi ke kolom 'Text' Anda
# Menerapkan fungsi 'remove' ke setiap nilai dalam kolom 'Text' pada DataFrame 'tweet'
tweet.loc[:, 'Text'] = tweet['Text'].apply(remove)

# Menghapus baris di mana kolom 'Text' tidak lagi isi karena penghapusan keyword
tweet = tweet[tweet['Text'] != ""]

# Menampilkan dataframe yang diperbarui
print(f"Jumlah data setelah eliminasi kata kunci tidak relevan : {tweet.shape[0]}")

tweet

"""# Case Folding"""

# Using Series.str.lower() function on Pandas
tweet['Text Case Folding'] = tweet['Text'].str.lower()

# Case Folding Result
tweet['Text Case Folding'].head()

"""# Text Clening"""

import string

def remove_tweet_special(text):
    # remove tab, new line, ans back slice
    text = text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")
    # remove non ASCII (emoticon, chinese word, .etc)
    text = text.encode('ascii', 'replace').decode('ascii')
    # remove mention, link, hashtag
    text = ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", text).split())
    # remove incomplete URL
    return text.replace("http://", " ").replace("https://", " ")

tweet['Text Case Folding'] = tweet['Text Case Folding'].apply(remove_tweet_special)

#remove number
def remove_number(text):
    return  re.sub(r"\d+", "", text)

tweet['Text Case Folding'] = tweet['Text Case Folding'].apply(remove_number)

#remove punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans("","",string.punctuation))

tweet['Text Case Folding'] = tweet['Text Case Folding'].apply(remove_punctuation)

#remove whitespace leading & trailing
def remove_whitespace_LT(text):
    return text.strip()

tweet['Text Case Folding'] = tweet['Text Case Folding'].apply(remove_whitespace_LT)

#remove multiple whitespace into single whitespace
def remove_whitespace_multiple(text):
    return re.sub('\s+',' ',text)

tweet['Text Case Folding'] = tweet['Text Case Folding'].apply(remove_whitespace_multiple)

# remove single char
def remove_singl_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

tweet['Text Cleaning'] = tweet['Text Case Folding'].apply(remove_singl_char)
# Cleaning Result
tweet['Text Cleaning'].head()

"""# Tokenizing"""

import re #regex library
import nltk
nltk.download("punkt_tab")
from nltk.tokenize import word_tokenize # import word_tokenize

# NLTK word rokenize
def word_tokenize_wrapper(text):
    return word_tokenize(text)

tweet['Text Tokenizing'] = tweet['Text Cleaning'].apply(word_tokenize_wrapper)

# Tokenizing Result
tweet['Text Tokenizing'].head()

"""# Normalization"""

normalizad_word = pd.read_excel("/content/drive/MyDrive/TTU 2/kamuskatabaku.xlsx")

normalizad_word_dict = {}

for index, row in normalizad_word.iterrows():
    if row[0] not in normalizad_word_dict:
        normalizad_word_dict[row[0]] = row[1]

def normalized_term(document):
    return [normalizad_word_dict[term] if term in normalizad_word_dict else term for term in document]

tweet['Text Normalization'] = tweet['Text Tokenizing'].apply(normalized_term)

# Tokenizing Result
tweet['Text Normalization'].head()

"""# Stemming"""

# import Sastrawi package
!pip install Sastrawi
!pip install swifter
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import swifter

# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# stemmed
def stemmed_wrapper(term):
    return stemmer.stem(term)

term_dict = {}

for document in tweet['Text Normalization']:
    for term in document:
        if term not in term_dict:
            term_dict[term] = ' '

print(len(term_dict))
print("------------------------")

for term in term_dict:
    term_dict[term] = stemmed_wrapper(term)
    print(term,":" ,term_dict[term])

print(term_dict)
print("------------------------")

# apply stemmed term to dataframe
def get_stemmed_term(document):
    return [term_dict[term] for term in document]

tweet['Text Stemming'] = tweet['Text Normalization'].swifter.apply(get_stemmed_term)
print(tweet['Text Stemming'])

"""# Filtering"""

from nltk.corpus import stopwords
nltk.download('stopwords')

# ----------------------- get stopword from NLTK stopword -------------------------------
# get stopword indonesia
list_stopwords = stopwords.words('indonesian')


# ---------------------------- manualy add stopword  ------------------------------------
# append additional stopword
list_stopwords.extend(["yg", "dg", "rt", "dgn", "ny", 'klo', 'kalo', 'amp', 'biar', 'bikin',
                       'bilang', 'gak', 'ga', 'krn', 'nya', 'nih', 'sih','si', 'tau', 'tdk',
                       'tuh', 'utk', 'ya', 'jd', 'jgn', 'sdh', 'aja', 'nyg', 'hehe', 'pen',
                       'u', 'nan', 'loh', 'rt', '&amp', 'yah', 'sdgkan', 'sdg', 'emg', 'sm',
                       'pls', 'mlu', 'ken', 'allah', 'brb', 'btw', 'b/c', 'cod', 'cmiiw',
                       'fyi', 'gg', 'ggwp', 'idk', 'ikr', 'lol', 'ootd', 'lmao', 'oot', 'pap',
                       'otw', 'tfl', 'vc', 'ygy', 'ah'])

# ----------------------- add stopword from txt file ------------------------------------
# read txt stopword using pandas
txt_stopword = pd.read_csv("/content/drive/MyDrive/TTU 2/stopwordbahasa.txt", names= ["stopwords"], header = None)

# convert stopword string to list & append additional stopword
list_stopwords.extend(txt_stopword["stopwords"][0].split(' '))

# ---------------------------------------------------------------------------------------

# convert list to dictionary
list_stopwords = set(list_stopwords)


#remove stopword pada list token
def stopwords_removal(words):
    return [word for word in words if word not in list_stopwords]

tweet['Text Filtering'] = tweet['Text Stemming'].apply(stopwords_removal)


tweet['Text Filtering']

"""# View Preprocessing Results"""

tweet

"""# Save Preprocessing Results"""

tweet.to_csv("preprocessing results", index=False)

"""# Delete Unnecessary Data"""

df= tweet.drop(columns=['Text', 'Text Case Folding', 'Text Cleaning', 'Text Tokenizing', 'Text Normalization', 'Text Stemming'])
df.head()

"""# Labeling Using Inset Lexicon"""

lexicon_positive = pd.read_excel('/content/drive/MyDrive/TTU 2/kamus_positive.xlsx')
lexicon_positive_dict = {}
for index, row in lexicon_positive.iterrows():
    if row[0] not in lexicon_positive_dict:
        lexicon_positive_dict[row[0]] = row[1]

lexicon_negative = pd.read_excel('/content/drive/MyDrive/TTU 2/kamus_negative.xlsx')
lexicon_negative_dict = {}
for index, row in lexicon_negative.iterrows():
    if row[0] not in lexicon_negative_dict:
        lexicon_negative_dict[row[0]] = row[1]

def sentiment_analysis_lexicon_indonesia(text):
    score = 0
    for word in text:
        if (word in lexicon_positive_dict):
            score = score + lexicon_positive_dict[word]
    for word in text:
        if (word in lexicon_negative_dict):
            score = score + lexicon_negative_dict[word]
    sentimen=''
    if (score >= 0):
        sentimen = 'Positive'
    else:
        sentimen = 'Negative'
    return score, sentimen

results = df['Text Filtering'].apply(sentiment_analysis_lexicon_indonesia)
results = list(zip(*results))
df['Polarity Score'] = results[0]
df['Indonesia Sentiment'] = results[1]

df[['Text Filtering','Polarity Score','Indonesia Sentiment']]

"""## Sentiment Cumulative Results"""

inset_counts = df['Indonesia Sentiment'].value_counts()
inset_counts

"""## Save Labeling Results"""

df.to_csv("sentiment results", index=False)

"""## Labeling Results Visualization"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd # Import pandas to read the CSV

# Load the data from the CSV file
df_inset1 = pd.read_csv("sentiment results")

# Assuming 'df_inset1' has the 'Indonesia Sentiment' column
sentiment_counts = df_inset1['Indonesia Sentiment'].value_counts()

# Reorder sentiment_counts to ensure 'Positive' is first
sentiment_counts = sentiment_counts.reindex(['Positive', 'Negative'])

# Creating the pie chart
plt.figure(figsize=(8, 8))  # Adjust figure size if needed
colors = ['#66b3ff', 'red']  # Colors for Positive and Negative

# Creating the pie chart with autopct function for custom labels
def make_autopct(values):
    def my_autopct(pct):
        total = sum(values)
        val = int(round(pct*total/100.0))
        return '{v:d} ({p:.1f}%)'.format(p=pct,v=val) # Format diubah menjadi jumlah (persen)
    return my_autopct

plt.pie(sentiment_counts, labels=sentiment_counts.index,
        autopct=make_autopct(sentiment_counts), # Use custom autopct function
        startangle=90, colors=colors, textprops={'fontsize': 12})

# Adding a title
plt.title("Distribution of Tweets Sentiment", loc="center", fontsize=18,
          color="#000080", pad=20, fontweight='bold')

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np

df = pd.read_csv("sentiment results")

df

from wordcloud import WordCloud,STOPWORDS
import matplotlib.pyplot as plt
import seaborn as sns

new_df=df[df['Indonesia Sentiment']=='Positive']
words = ' '.join(new_df['Text Filtering'])
wordcloud = WordCloud(stopwords=STOPWORDS,
                      background_color='black',
                      width=3000, height=1500, max_words = 100, collocations=False
                     ).generate(words)
plt.figure(figsize=(15, 15))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis('off')
plt.show()

from wordcloud import WordCloud,STOPWORDS
import matplotlib.pyplot as plt
import seaborn as sns

new_df=df[df['Indonesia Sentiment']=='Negative']
words = ' '.join(new_df['Text Filtering'])
wordcloud = WordCloud(stopwords=STOPWORDS,
                      background_color='black',
                      width=3000, height=1500, max_words = 100, collocations=False
                     ).generate(words)
plt.figure(figsize=(15, 15))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis('off')
plt.show()

"""# N-Gram Analysis"""

def Gram_Analysis(Corpus, Gram, N):

  # Define Stopwords or import from nltk.corpus
  from nltk.corpus import stopwords
  from sklearn.feature_extraction.text import CountVectorizer #Import CountVectorizer
  Stopwords = stopwords.words('indonesian') # Or your desired list of stopwords

  # Vectorizer
  Vectorizer = CountVectorizer(ngram_range=(Gram, Gram))

  # Join the list of words in Corpus into a string before fit_transform
  Corpus = Corpus.apply(lambda x: ' '.join(x) if isinstance(x, list) else x)

  # N-Grams Matrix
  ngrams = Vectorizer.fit_transform(Corpus)

  # N-Grams Frequency
  Count = ngrams.sum(axis=0)

  # List of Words
  words = [(word, Count[0, idx]) for word, idx in Vectorizer.vocabulary_.items()]

  # Sort Descending With Key = Count
  words = sorted(words, key = lambda x:x[1], reverse = True)

  return sorted(words, key=lambda x: x[1], reverse=True)[:N]

# Use dropna() so the base DataFrame is not affected
Positive = df[df["Indonesia Sentiment"] == "Positive"].dropna()
Negative = df[df["Indonesia Sentiment"] == "Negative"].dropna()

"""## Unigram of Tweets Based on Sentiments"""

# Finding Unigram for Positive Sentiment
words = Gram_Analysis(Positive["Text Filtering"], 1, 20)
Unigram_positive = pd.DataFrame(words, columns=["Words", "Counts"])

# Visualization for Positive Sentiment
plt.figure(figsize=(12, 8))  # Adjust figure size for better readability

# Create the bar chart
bars = Unigram_positive.groupby("Words")["Counts"].sum().sort_values().plot(kind="barh", color="#66b3ff") # Use a more pleasant color

# Add labels to the end of each bar
for bar in bars.patches:
    plt.text(bar.get_width(), bar.get_y() + bar.get_height()/2,
             f'{int(bar.get_width())}',
             va = 'center', ha = 'left', fontsize = 10)

plt.title("Unigram of Tweets with Positive Sentiments",  # More descriptive title
          loc="center", fontsize=18, color="#000080", pad=20, fontweight='bold')  # Improved title formatting
plt.xlabel("Total Counts", color="#800080", fontsize=12, labelpad=15, fontweight='bold') # Improved x-label
plt.ylabel("Words", color="#008080", fontsize=12, labelpad=15, fontweight='bold')    # Improved y-label
plt.xticks(rotation=0)
plt.yticks(fontsize=10) # Improved y-axis tick size

plt.tight_layout()  # Adjust layout to prevent labels from being cut off
plt.show()

# Finding Unigram for Negative Sentiment
words = Gram_Analysis(Negative["Text Filtering"], 1, 20)
Unigram_negative = pd.DataFrame(words, columns=["Words", "Counts"])

# Visualization for Negative Sentiment
plt.figure(figsize=(12, 8))  # Adjust figure size for better readability

# Create the bar chart
bars = Unigram_negative.groupby("Words")["Counts"].sum().sort_values().plot(kind="barh", color="red") # Use a more pleasant color

# Add labels to the end of each bar
for bar in bars.patches:
    plt.text(bar.get_width(), bar.get_y() + bar.get_height()/2,
             f'{int(bar.get_width())}',
             va = 'center', ha = 'left', fontsize = 10)

plt.title("Unigram of Tweets with Negative Sentiments",  # More descriptive title
          loc="center", fontsize=18, color="#000080", pad=20, fontweight='bold')  # Improved title formatting
plt.xlabel("Total Counts", color="#800080", fontsize=12, labelpad=15, fontweight='bold') # Improved x-label
plt.ylabel("Words", color="#008080", fontsize=12, labelpad=15, fontweight='bold')    # Improved y-label
plt.xticks(rotation=0)
plt.yticks(fontsize=10) # Improved y-axis tick size

plt.tight_layout()  # Adjust layout to prevent labels from being cut off
plt.show()

"""## Bigram of Tweets Based On Sentiments"""

# Finding Bigram for Positive Sentiment
words = Gram_Analysis(Positive["Text Filtering"], 2, 20)
Bigram_positive = pd.DataFrame(words, columns=["Words", "Counts"])

# Visualization for Positive Sentiment
plt.figure(figsize=(12, 8))  # Adjust figure size for better readability

# Create the bar chart
bars = Bigram_positive.groupby("Words")["Counts"].sum().sort_values().plot(kind="barh", color="#66b3ff") # Use a more pleasant color

# Add labels to the end of each bar
for bar in bars.patches:
    plt.text(bar.get_width(), bar.get_y() + bar.get_height()/2,
             f'{int(bar.get_width())}',
             va = 'center', ha = 'left', fontsize = 10)

plt.title("Bigram of Tweets with Positive Sentiments",  # More descriptive title
          loc="center", fontsize=18, color="#000080", pad=20, fontweight='bold')  # Improved title formatting
plt.xlabel("Total Counts", color="#800080", fontsize=12, labelpad=15, fontweight='bold') # Improved x-label
plt.ylabel("Words", color="#008080", fontsize=12, labelpad=15, fontweight='bold')    # Improved y-label
plt.xticks(rotation=0)
plt.yticks(fontsize=10) # Improved y-axis tick size

plt.tight_layout()  # Adjust layout to prevent labels from being cut off
plt.show()

# Finding Bigram for Negative Sentiment
words = Gram_Analysis(Negative["Text Filtering"], 2, 20)
Bigram_negative = pd.DataFrame(words, columns=["Words", "Counts"])

# Visualization for Negative Sentiment
plt.figure(figsize=(12, 8))  # Adjust figure size for better readability

# Create the bar chart
bars = Bigram_negative.groupby("Words")["Counts"].sum().sort_values().plot(kind="barh", color="red") # Use a more pleasant color

# Add labels to the end of each bar
for bar in bars.patches:
    plt.text(bar.get_width(), bar.get_y() + bar.get_height()/2,
             f'{int(bar.get_width())}',
             va = 'center', ha = 'left', fontsize = 10)

plt.title("Bigram of Tweets with Negative Sentiments",  # More descriptive title
          loc="center", fontsize=18, color="#000080", pad=20, fontweight='bold')  # Improved title formatting
plt.xlabel("Total Counts", color="#800080", fontsize=12, labelpad=15, fontweight='bold') # Improved x-label
plt.ylabel("Words", color="#008080", fontsize=12, labelpad=15, fontweight='bold')    # Improved y-label
plt.xticks(rotation=0)
plt.yticks(fontsize=10) # Improved y-axis tick size

plt.tight_layout()  # Adjust layout to prevent labels from being cut off
plt.show()

"""## Trigram of Tweets Based On Sentiments"""

# Finding Trigram
words = Gram_Analysis(Positive["Text Filtering"], 3, 20)
Trigram_positive = pd.DataFrame(words, columns = ["Words", "Counts"])

# Visualization for Positive Sentiment
plt.figure(figsize=(12, 8))  # Adjust figure size for better readability

# Create the bar chart
bars = Trigram_positive.groupby("Words")["Counts"].sum().sort_values().plot(kind="barh", color="#66b3ff") # Use a more pleasant color

# Add labels to the end of each bar
for bar in bars.patches:
    plt.text(bar.get_width(), bar.get_y() + bar.get_height()/2,
             f'{int(bar.get_width())}',
             va = 'center', ha = 'left', fontsize=10)

plt.title("Trigram of Tweets with Positive Sentiments",  # More descriptive title
          loc="center", fontsize=18, color="#000080", pad=20, fontweight='bold')  # Improved title formatting
plt.xlabel("Total Counts", color="#800080", fontsize=12, labelpad=15, fontweight='bold') # Improved x-label
plt.ylabel("Words", color="#008080", fontsize=12, labelpad=15, fontweight='bold')    # Improved y-label
plt.xticks(rotation=0)
plt.yticks(fontsize=10) # Improved y-axis tick size

plt.tight_layout()  # Adjust layout to prevent labels from being cut off
plt.show()

# Finding Trigram
words = Gram_Analysis(Negative["Text Filtering"], 3, 20)
Trigram_negative = pd.DataFrame(words, columns = ["Words", "Counts"])

# Visualization for Negative Sentiment
plt.figure(figsize=(12, 8))  # Adjust figure size for better readability

# Create the bar chart
bars = Trigram_negative.groupby("Words")["Counts"].sum().sort_values().plot(kind="barh", color="red") # Use a more pleasant color

# Add labels to the end of each bar
for bar in bars.patches:
    plt.text(bar.get_width(), bar.get_y() + bar.get_height()/2,
             f'{int(bar.get_width())}',
             va = 'center', ha = 'left', fontsize=10)

plt.title("Trigram of Tweets with Negative Sentiments",  # More descriptive title
          loc="center", fontsize=18, color="#000080", pad=20, fontweight='bold')  # Improved title formatting
plt.xlabel("Total Counts", color="#800080", fontsize=12, labelpad=15, fontweight='bold') # Improved x-label
plt.ylabel("Words", color="#008080", fontsize=12, labelpad=15, fontweight='bold')    # Improved y-label
plt.xticks(rotation=0)
plt.yticks(fontsize=10) # Improved y-axis tick size

plt.tight_layout()  # Adjust layout to prevent labels from being cut off
plt.show()

"""# Modeling Data

## Inset TF-IDF
"""

import pandas as pd
import numpy as np

df_inset1 = pd.read_csv("sentiment results")

df_inset1

"""## Splitting the Data"""

# Define Y (This is the value we will predict)
X = df_inset1["Text Filtering"]
y = df_inset1["Indonesia Sentiment"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print("Train Data:", len(X_train))
print("Test Data:", len(X_test))

"""## Implementation TF-IDF"""

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer (max_features=2500, min_df=7, max_df=0.8, stop_words=stopwords.words('indonesian'))
response = tfidf_vectorizer.fit_transform(X_train)

df_tfidf = pd.DataFrame(response.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
df_tfidf.head()

"""## Tranforming the Dataset"""

X_train = tfidf_vectorizer.transform(X_train)
X_test  = tfidf_vectorizer.transform(X_test)
print(f'Inset TF IDF Data Transformed.')

"""## Evaluate Model Function"""

from sklearn.ensemble import RandomForestClassifier

text_classifier1 = RandomForestClassifier(n_estimators=200, criterion='entropy', random_state=0)
text_classifier1.fit(X_train, y_train)

tfidf_predictions = text_classifier1.predict(X_test)

"""## Random Forest Model"""

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

cm1 = confusion_matrix(y_test,tfidf_predictions)
cr1 = classification_report(y_test,tfidf_predictions)
rf_tfidf1 = accuracy_score(y_test,tfidf_predictions)
print('Confusion matrix: \n',cm1)
print('Classification report: \n',cr1)
print(f'Inset Random Forest Classifier on TF-IDF Vectors: {rf_tfidf1}')

# plot confusion matrix
plt.figure(figsize=(6,4))
sentiment_classes = ['Negative', 'Positive']
sns.heatmap(cm1, cmap=plt.cm.Reds, annot=True, fmt='d',
            xticklabels=sentiment_classes,
            yticklabels=sentiment_classes)
plt.title('Confusion Matrix', fontsize=16)
plt.ylabel('Aktual Label', fontsize=12)
plt.xlabel('Predicted Label', fontsize=12)
plt.show()

"""## Word Weighting Results"""

import pandas as pd
model = {'Model':['Inset Random Forest Classifier - TFIDF Vectors'],
         'Accuracy Score':[rf_tfidf1]
         }
model_df = pd.DataFrame(model)
model_df

"""# Hyperparameter Tuning"""

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression


Param = {"C": np.logspace(-4, 4, 50), "penalty": ['l1', 'l2']}
grid_search = GridSearchCV(estimator = LogisticRegression(random_state = 42), param_grid = Param, scoring = "accuracy", cv = 10, verbose = 0, n_jobs = -1)

grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)